# Generated by Django 2.1.7 on 2020-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CofndProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourself', models.CharField(blank=True, choices=[('student', 'student'), ('enterpreneur', 'enterpreneur'), ('Businessman', 'Businessman')], max_length=100)),
                ('looking_for', models.CharField(blank=True, choices=[('startup-idea', 'startup-idea'), ('startup-company', 'startup-company')], max_length=100)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('join_as', models.CharField(blank=True, choices=[('cofounder', 'cofounder'), ('team-member', 'team-member'), ('partner', 'partner'), ('others', 'others')], max_length=100)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('employment', models.CharField(blank=True, max_length=200)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('passing_year', models.DateTimeField()),
                ('grade', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(blank=True, max_length=100, unique=True)),
                ('cmp_address', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('Businesstype', models.CharField(blank=True, max_length=200)),
                ('About_cmp', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EduDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('passing_year', models.DateTimeField()),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('about', models.CharField(blank=True, choices=[('student', 'student'), ('enterpreneur', 'enterpreneur'), ('Businessman', 'Businessman')], max_length=100)),
                ('profile_as', models.CharField(blank=True, choices=[('student', 'student'), ('enterpreneur', 'enterpreneur'), ('Businessman', 'Businessman'), ('Investor', 'Investor'), ('Freelancers', 'Freelancers'), ('Student Enterpreneur', 'Student Enterpreneur')], max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('Contact', models.IntegerField(blank=True, unique=True)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
