# Generated by Django 2.1.7 on 2020-07-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_auto_20200710_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='Companyname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='Company',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyInfo', to='forms.CompanyBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileInfo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
