# Generated by Django 2.1.7 on 2020-07-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200710_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userprofile',
        ),
    ]
