# Generated by Django 2.1.7 on 2020-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200710_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Contact',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
