# Generated by Django 2.1.7 on 2020-07-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200710_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
