# Generated by Django 2.1.7 on 2020-07-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0009_auto_20200710_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofndprofile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Cofounder_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
