# Generated by Django 2.1.7 on 2020-07-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_cofndprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cmp_name', models.CharField(blank=True, max_length=200)),
                ('product_pic', models.ImageField(blank=True, upload_to='product_pics')),
                ('Prod_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('Description', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
