# Generated by Django 2.1.7 on 2020-07-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Cmp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_cmp', to='forms.CompanyBase'),
        ),
    ]
