# Generated by Django 2.1.7 on 2020-07-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20200711_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Cmp_name',
            new_name='productcompany',
        ),
    ]
